apiVersion: v1
kind: Service
metadata:
  name: hirequest-backend
  namespace: hirequest
spec:
  selector:
    app: hirequest-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP