"""
interview.py

Interview API endpoints.

Responsibilities:
- Persist candidate answers
- Generate the next interview question
- Determine interview completion
- Generate and store interview summaries
- Retrieve resume context for grounded question generation

Interview Flow:
1. Candidate submits an answer
2. Interview history is retrieved
3. Completion status is evaluated
4. Resume context is retrieved
5. Router chain generates either:
   - Next interview question
   - Final interview summary
6. Results are persisted and returned
"""

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from backend.db.db import get_db
from backend.db.crud import (
    get_history,
    save_answer,
    format_history_for_prompt,
    get_interview_config,
    save_interview_summary,
)
from backend.schemas.schemas import (
    InterviewRequest,
    AnswerRequest,
    InterviewResponse,
)
from backend.services.router_chain import router_chain
from backend.middleware.vectorstore import get_resume_context


router = APIRouter()


@router.post("/answer")
def submit_answer(
    req: AnswerRequest,
    db: Session = Depends(get_db),
):
    """
    Persist a candidate's answer to the previously
    generated interview question.

    Args:
        req:
            Candidate answer payload.

        db:
            Active database session.

    Returns:
        dict:
            Status confirmation.
    """

    save_answer(
        db,
        req.candidate_id,
        req.role,
        req.question,
        req.answer,
    )

    return {"status": "answer saved"}


@router.post("/{candidate_id}/question")
def next_question(
    candidate_id: int,
    req: InterviewRequest,
    db: Session = Depends(get_db),
):
    """
    Generate the next interview response.

    Depending on interview progress, the router chain
    will either generate:

    - A follow-up interview question
    - A final interview summary

    Args:
        candidate_id:
            Candidate identifier.

        req:
            Interview request payload.

        db:
            Active database session.

    Returns:
        InterviewResponse | dict:
            Next interview question or completion payload.
    """

    history = get_history(db, candidate_id)

    config = get_interview_config(
        db,
        candidate_id,
        req.role,
    )

    # Count unanswered questions generated by the system.
    # Once the configured question limit is reached,
    # the interview transitions into summary mode.
    question_count = sum(
        1
        for h in history[1:]  # Skip initial greeting entry
        if h.get("question") and not h.get("answer")
    )

    mode = (
        "summary"
        if question_count >= config.n_questions
        else "question"
    )

    # Retrieve resume content to ground generation
    # in the candidate's actual experience.
    retrieved_context = get_resume_context(
        req.candidate_id,
        req.role,
        k=10,
    )

    payload = {
        "role": req.role,
        "resume_context": retrieved_context,
        "history": format_history_for_prompt(history),
        "mode": mode,
    }

    result = router_chain.invoke(payload)

    # Interview completion path
    if mode == "summary":

        strengths = result["strengths"]
        improvements = result["improvements"]
        overall = result["overall"]

        # Persist a recruiter-friendly summary
        # for later review and reporting.
        summary_text = (
            f"Strengths: {', '.join(strengths)}\n"
            f"Improvements: {', '.join(improvements)}\n"
            f"Overall: {overall}"
        )

        save_interview_summary(
            db,
            candidate_id,
            req.role,
            summary_text,
        )

        return {
            "status": "complete",
            "summary": summary_text,
            "closing": result.get(
                "closing",
                (
                    f"Thank you, this concludes "
                    f"your {req.role} interview."
                ),
            ),
        }

    # Interview continuation path
    else:

        # Persist generated question immediately so
        # interview state remains recoverable even if
        # the candidate disconnects before answering.
        save_answer(
            db,
            candidate_id,
            req.role,
            result["question"],
            None,
        )

        return InterviewResponse(**result)